// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

#import "MSBEffectType.h"
#import "MSBParamOfEqualizer.h"
#import "MSBParamOfGain.h"
#import "MSBParamOfReverb.h"
#import <Foundation/Foundation.h>
@class MSBEffectNode;


@interface MSBEffectNode : NSObject

- (BOOL)setEffectParamReverb:(nonnull MSBParamOfReverb *)param;

- (BOOL)setEffectParamEqualizer:(nonnull MSBParamOfEqualizer *)param;

- (BOOL)setEffectParamGain:(nonnull MSBParamOfGain *)param;

+ (nullable MSBEffectNode *)createEffectNode:(MSBEffectType)type;

@end
