// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

#import <Foundation/Foundation.h>
@class MSBEffectManager;
@class MSBEffectNode;


@interface MSBEffectManager : NSObject

- (nonnull NSData *)effectProcess:(nonnull NSData *)inData
                      inSampleCnt:(int32_t)inSampleCnt;

- (BOOL)init:(nonnull NSString *)inputFileName
outputFileName:(nonnull NSString *)outputFileName;

- (int32_t)audioSeek:(int32_t)seekPos;

- (nonnull NSData *)getEffectData:(int32_t)sampleCount;

- (BOOL)generateEffectFile;

- (void)addEffectNode:(nullable MSBEffectNode *)node;

+ (nullable MSBEffectManager *)createEffectManager;

@end
