// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MSBEffectType)
{
    MSBEffectTypeReverb,
    MSBEffectTypeEqualizer,
    MSBEffectTypeGain,
};
