// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

#import <Foundation/Foundation.h>

@interface MSBVoiceAssetInfo : NSObject
- (nonnull instancetype)initWithAssetId:(int32_t)assetId
                              assetName:(nonnull NSString *)assetName;
+ (nonnull instancetype)voiceAssetInfoWithAssetId:(int32_t)assetId
                                        assetName:(nonnull NSString *)assetName;

@property (nonatomic, readonly) int32_t assetId;

@property (nonatomic, readonly, nonnull) NSString * assetName;

@end
