// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

#import "MSBVoiceAnalysisInfo.h"
#import "MSBVoiceAssetInfo.h"
#import <Foundation/Foundation.h>

@interface MSBVoiceInputInfo : NSObject
- (nonnull instancetype)initWithMidiFileName:(nonnull NSString *)midiFileName
                              configFileName:(nonnull NSString *)configFileName
                                  assetInfos:(nonnull NSArray<MSBVoiceAssetInfo *> *)assetInfos
                               analysisInfos:(nonnull NSArray<MSBVoiceAnalysisInfo *> *)analysisInfos
                                 outFileName:(nonnull NSString *)outFileName;
+ (nonnull instancetype)voiceInputInfoWithMidiFileName:(nonnull NSString *)midiFileName
                                        configFileName:(nonnull NSString *)configFileName
                                            assetInfos:(nonnull NSArray<MSBVoiceAssetInfo *> *)assetInfos
                                         analysisInfos:(nonnull NSArray<MSBVoiceAnalysisInfo *> *)analysisInfos
                                           outFileName:(nonnull NSString *)outFileName;

@property (nonatomic, readonly, nonnull) NSString * midiFileName;

@property (nonatomic, readonly, nonnull) NSString * configFileName;

@property (nonatomic, readonly, nonnull) NSArray<MSBVoiceAssetInfo *> * assetInfos;

@property (nonatomic, readonly, nonnull) NSArray<MSBVoiceAnalysisInfo *> * analysisInfos;

@property (nonatomic, readonly, nonnull) NSString * outFileName;

@end
