// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

#import <Foundation/Foundation.h>

@interface MSBParamOfGain : NSObject
- (nonnull instancetype)initWithGain:(float)gain
                             limiter:(BOOL)limiter;
+ (nonnull instancetype)paramOfGainWithGain:(float)gain
                                    limiter:(BOOL)limiter;

@property (nonatomic, readonly) float gain;

@property (nonatomic, readonly) BOOL limiter;

@end
