// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

#import <Foundation/Foundation.h>

@interface MSBParamOfReverb : NSObject
- (nonnull instancetype)initWithReverberance:(int32_t)reverberance
                                   hfDamping:(int32_t)hfDamping
                                   roomScale:(int32_t)roomScale
                                     delayMs:(int32_t)delayMs;
+ (nonnull instancetype)paramOfReverbWithReverberance:(int32_t)reverberance
                                            hfDamping:(int32_t)hfDamping
                                            roomScale:(int32_t)roomScale
                                              delayMs:(int32_t)delayMs;

@property (nonatomic, readonly) int32_t reverberance;

@property (nonatomic, readonly) int32_t hfDamping;

@property (nonatomic, readonly) int32_t roomScale;

@property (nonatomic, readonly) int32_t delayMs;

@end
