// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

#import "MSBVoiceAssetInfo.h"
#import <Foundation/Foundation.h>
@class MSBVoicePreprocess;


@interface MSBVoicePreprocess : NSObject

+ (nullable MSBVoicePreprocess *)createVoicePreprocess;

- (int32_t)init:(int32_t)sampleRate
        channel:(int32_t)channel;

- (nonnull NSData *)preProcess:(nonnull NSData *)inData
                   inSampleCnt:(int32_t)inSampleCnt;

- (nonnull NSData *)preProcessAgc:(nonnull NSData *)inData
                      inSampleCnt:(int32_t)inSampleCnt;

- (nonnull NSData *)preProcessAns:(nonnull NSData *)inData
                      inSampleCnt:(int32_t)inSampleCnt;

- (nonnull NSData *)preProcessAnsAssetInfo:(nonnull MSBVoiceAssetInfo *)assetInfo;

- (nonnull NSData *)preProcessAec:(nonnull NSData *)inFarData
                   inFarSampleCnt:(int32_t)inFarSampleCnt
                       inNearData:(nonnull NSData *)inNearData
                  inNearSampleCnt:(int32_t)inNearSampleCnt
                         filePath:(nonnull NSString *)filePath
                     InSndCardBuf:(int32_t)InSndCardBuf;

- (void)mainAec:(nonnull NSString *)fFar
          fNear:(nonnull NSString *)fNear
           fOut:(nonnull NSString *)fOut;

- (BOOL)audioMix:(nonnull NSArray<NSString *> *)audioNames
          output:(nonnull NSString *)output;

- (int32_t)preProcessVod:(nonnull NSData *)inData
             inSampleCnt:(int32_t)inSampleCnt;

- (int32_t)resampleInit:(int32_t)srcRate
                dstRate:(int32_t)dstRate
        maxSrcNbSamples:(int32_t)maxSrcNbSamples
            srcChannels:(int32_t)srcChannels
            dstChannels:(int32_t)dstChannels
              srcFormat:(int32_t)srcFormat
              dstFormat:(int32_t)dstFormat;

- (nonnull NSData *)resampleProcess:(nonnull NSData *)srcData
                        srcDataSize:(int32_t)srcDataSize
                       srcNbSamples:(int32_t)srcNbSamples;

- (void)resampleDestroy;

- (nonnull NSData *)processAudioDecode:(nonnull NSString *)path
                               dstRate:(int32_t)dstRate
                           dstChannels:(int32_t)dstChannels
                             dstFormat:(int32_t)dstFormat;

@end
