// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

#import "MSBVoiceNoteInfo.h"
#import "MSBVoicePitchInfo.h"
#import "MSBVoiceVadInfo.h"
#import <Foundation/Foundation.h>

@interface MSBVoiceAnalysisInfo : NSObject
- (nonnull instancetype)initWithStartTimeMs:(int32_t)startTimeMs
                       consonantStartTimeMs:(int32_t)consonantStartTimeMs
                           vowelStartTimeMs:(int32_t)vowelStartTimeMs
                                  endTimeMs:(int32_t)endTimeMs
                                   pitchSeq:(nonnull NSArray<MSBVoicePitchInfo *> *)pitchSeq
                                    noteSeq:(nonnull NSArray<MSBVoiceNoteInfo *> *)noteSeq
                                  vadResult:(nonnull NSArray<MSBVoiceVadInfo *> *)vadResult
                                     bValid:(BOOL)bValid
                                    assetId:(int32_t)assetId
                                  voiceName:(nonnull NSString *)voiceName;
+ (nonnull instancetype)voiceAnalysisInfoWithStartTimeMs:(int32_t)startTimeMs
                                    consonantStartTimeMs:(int32_t)consonantStartTimeMs
                                        vowelStartTimeMs:(int32_t)vowelStartTimeMs
                                               endTimeMs:(int32_t)endTimeMs
                                                pitchSeq:(nonnull NSArray<MSBVoicePitchInfo *> *)pitchSeq
                                                 noteSeq:(nonnull NSArray<MSBVoiceNoteInfo *> *)noteSeq
                                               vadResult:(nonnull NSArray<MSBVoiceVadInfo *> *)vadResult
                                                  bValid:(BOOL)bValid
                                                 assetId:(int32_t)assetId
                                               voiceName:(nonnull NSString *)voiceName;

@property (nonatomic, readonly) int32_t startTimeMs;

@property (nonatomic, readonly) int32_t consonantStartTimeMs;

@property (nonatomic, readonly) int32_t vowelStartTimeMs;

@property (nonatomic, readonly) int32_t endTimeMs;

@property (nonatomic, readonly, nonnull) NSArray<MSBVoicePitchInfo *> * pitchSeq;

@property (nonatomic, readonly, nonnull) NSArray<MSBVoiceNoteInfo *> * noteSeq;

@property (nonatomic, readonly, nonnull) NSArray<MSBVoiceVadInfo *> * vadResult;

@property (nonatomic, readonly) BOOL bValid;

@property (nonatomic, readonly) int32_t assetId;

@property (nonatomic, readonly, nonnull) NSString * voiceName;

@end
