// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

#import <Foundation/Foundation.h>

@interface MSBVoiceAnalysisPitchAndNoteInfo : NSObject
- (nonnull instancetype)initWithMOutpitch:(float)mOutpitch
                                 mOutnote:(float)mOutnote
                         mOutoctaveString:(nonnull NSString *)mOutoctaveString
                           mOutnoteString:(nonnull NSString *)mOutnoteString;
+ (nonnull instancetype)VoiceAnalysisPitchAndNoteInfoWithMOutpitch:(float)mOutpitch
                                                          mOutnote:(float)mOutnote
                                                  mOutoctaveString:(nonnull NSString *)mOutoctaveString
                                                    mOutnoteString:(nonnull NSString *)mOutnoteString;

@property (nonatomic, readonly) float mOutpitch;

@property (nonatomic, readonly) float mOutnote;

@property (nonatomic, readonly, nonnull) NSString * mOutoctaveString;

@property (nonatomic, readonly, nonnull) NSString * mOutnoteString;

@end
