// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

#import "MSBVoiceAnalysisInfo.h"
#import "MSBVoiceAssetInfo.h"
#import "MSBVoiceInputInfo.h"
#import "MSBVoiceTrackInfo.h"
#import <Foundation/Foundation.h>
@class MSBVoiceBeatProcess;
@protocol MSBNotifyCallback;


@interface MSBVoiceBeatProcess : NSObject

+ (nullable MSBVoiceBeatProcess *)createVoiceBeatProcess;

- (void)generateBeatingVoice;

- (nonnull MSBVoiceAnalysisInfo *)generateVoiceAnalysisInfo:(nonnull MSBVoiceAssetInfo *)assetInfo;

- (nonnull NSDictionary<NSNumber *, NSArray<MSBVoiceTrackInfo *> *> *)getVoiceTrackInfo:(nonnull MSBVoiceInputInfo *)inputinfo;

- (nonnull NSData *)getAudioData:(int32_t)sampleCount;

- (int32_t)getAudioDuration;

- (int32_t)audioSeek:(int32_t)seekPos;

- (BOOL)stopThread;

- (void)setCallback:(nullable id<MSBNotifyCallback>)outputCallback;

@end
