// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

#import "MSBVoiceNodeInfo.h"
#import <Foundation/Foundation.h>

@interface MSBVoiceTrackInfo : NSObject
- (nonnull instancetype)initWithTrackId:(int32_t)trackId
                              voiceInfo:(nonnull NSArray<MSBVoiceNodeInfo *> *)voiceInfo;
+ (nonnull instancetype)voiceTrackInfoWithTrackId:(int32_t)trackId
                                        voiceInfo:(nonnull NSArray<MSBVoiceNodeInfo *> *)voiceInfo;

@property (nonatomic, readonly) int32_t trackId;

@property (nonatomic, readonly, nonnull) NSArray<MSBVoiceNodeInfo *> * voiceInfo;

@end
